### PR TITLE
Add implementation help to ReadMe

### PR DESCRIPTION
**Pull request by JohnPettigrew**
This patch tries to provide more implementation help in the ReadMe file.

- Changed section title from Usage to Configuration for accuracy.
- Clarified Session Storage section, rearranged the options in the list (to go from most general to most specific), and added a new option for disabling session storage only for JSON requests.
- Added a new Usage section with suggestions for implementing login and how to extract information from the JWT token when an authorised request is received.

### CODE REVIEW

**Comment by waiting-for-dev** [comment]
Thanks! I'll review it as soon as possible

**Comment by JohnPettigrew** [comment]
@waiting-for-dev Browsing old PRs, I found [112](https://github.com/waiting-for-dev/devise-jwt/pull/112), which suggested the same additional session-storage strategy I suggest here. Presumably, therefore, you'll want to revert those lines (177-189), although I hope the rest of the PR meets with your approval!

**Comment by indie-rok** [comment]
@JohnPettigrew It would be nice to add that you can just do `current_user.id` without all the token parse and it will give you the user id as well

**Comment by waiting-for-dev** [comment]
Sorry, not going to merge it for now. I'm planning on going through the Readme any time soon.

**Pull request closed without merging**
