### PR TITLE
Added code generators for revocation strategies

### PR DESCRIPTION
**Pull request by kopylovvlad**
Hello. Thank you for the useful gem.
I added 3 code generators for revocation strategies (jti_matcher, whitelist and blacklist).
Here is my pull request. I hope, it will be useful.

### CODE REVIEW

**Comment by kopylovvlad** [comment]
I refactored my code by rubocop and reek and refactored lib/devise/jwt/defaults_generator.rb file.

**Comment by kopylovvlad** [comment]
Hi, @waiting-for-dev.
Alright, I understood. Maybe, the better way was creating an issue and then to to create PL. Though, it was a good practice with generators. The idea about another gem is good, I need time to think about it.

I noticed, the repository uses Travis CI. The file 'lib/devise/jwt/defaults_generator.rb' can't pass the analyze with RuboCop. It gives 4 "Layout/EmptyLineAfterGuardClause" offenses. If you do not mind, I can create one little PL with fixes.

**Comment by waiting-for-dev** [comment]
Thanks for understanding @kopylovvlad . It would be great to see that PR. From time to time rubocop/reek offenses arise in old code due to their Gemfile version config (which keep going updating and they now consider an offense something it wasn't before).

Cheers!

**Comment by waiting-for-dev** [comment]
Closing it, but if you finally extract the feature to a Gemfile please tell me so we can link it from the Readme.

**Comment by TheSmartnik** [comment]
Hi, thanks for gem! I'd like to argue that we still need generator. It's shame this pr hasn't been merged.

Generators would allow for a gentler learning curve, which it extremely important for adaptation of any new technology. Plus it's extremely inconvenient to setup the same jwt models over and over again in every project as rarely change in a simple SPAs.

>They add complexity to the library. This is all new code we have to maintain and keep sync with changes in the rest of features.

The library is mature and generators are fundamentals, that won't change very often. We can estimate it by looking at how often README.md was changed because of the migrations. And for the last couple of years, it happened once. A lot of benefits without much costs.

> They encourage people to program without knowing what they are doing. This is specially sensible in a library like this one which deals with security related concepts.

The library is secure by default, so I would argue that it's a big problem. Everyone still just copy pastes code from the README.

> They are not very useful when your scenario is a little different from the general one.

It's probably relates to advanced users, who would be able to easily make changes themselves, but would still benefit from generated files. Much like in rails, devise, rspes and other gems

**Comment by waiting-for-dev** [comment]
I'm sorry, I still think the same. I think generators are useful for frameworks or huge libraries, but not for tiny libraries like this one. As always, it is a trade-off, and for small libraries I think than generator benefits don't pay off. But, as I said before, you can extract this PR to another gem which I'd have no problems to reference from the Readme.

**Pull request closed without merging**
