### PR TITLE
Avoid destroy action if no matched jwt

### PR DESCRIPTION
**Pull request by vshy108**
jwt is nil if sign out more than once.

### CODE REVIEW

**Comment by waiting-for-dev** [comment]
Hi @vshy108 ,

thanks for your PR. In which situation a user will request a sign out with a JWT that has been already revoked?

**Comment by vshy108** [comment]
multiple sign out requests from same client device?

**Comment by waiting-for-dev** [comment]
I see, I guess that with an impatient user :)

Two considerations about the PR:

- Could you use something different than `.present?`?. This method comes from `ActiveSupport`. Even if usually it will be available because the gem is meant to be used with rails, it could not be the case in some corner case scenario (and there are ruby core alternatives).
- Could you add a unit test?

Thanks

**Comment by vshy108** [comment]
I tried to use `.empty?`, `.size == 0`, `.count == 0` but all of them are fail to pass the rspec test while `.present?` is the only way I found can pass the rspec test. Will study further for alternatives to check the existence.

**Comment by waiting-for-dev** [comment]
`find_by` does not return an array: it returns the record or `nil` if it doesn't exist. So you can do a regular `if` check, for instance.

**Comment by vshy108** [comment]
Thanks for the tips, I updated my pull request by removing .present usage and adding a related unit test.

**Comment by vshy108** [comment]
I tried to use jwt&.destroy! when I saw rubocop reported errors but it seems like only support by ruby 2.4.0

**Comment by waiting-for-dev** [comment]
Thanks @vshy108 , PR merged. You are right, I disabled SafeNavitation cop to support more ruby versions.

**Comment by waiting-for-dev** [comment]
I want to check another issue and then I'll release a new version with this addition. I'll report here.

**Comment by waiting-for-dev** [comment]
Released in version `0.5.3`

**Pull request merged**
